[workspace]
members = [
    "lib",
    "part1",
    "part2",
    "part3",
    "part4",
    "part5",
    "part6",
    "part7",
    "part8",
    "part9",
    "part10",
    "part11",
    "part12",
    "part13",
    "part14",
    "final",
]
resolver = "2"

[profile.release]
debug = true
lto = true
