# Current triple can be printed with: rustc -vV

[target.x86_64-unknown-linux-gnu]
# Use native CPU
rustflags = ["-Ctarget-cpu=native"]

[target.aarch64-apple-darwin]
# Use native CPU
rustflags = ["-Ctarget-cpu=native"]

